### ISSUE TITLE
*com - has PAM enabled

### ISSUE THREAD

**Issue by garywmendel** [garywmendel/Yopine#10]
PAM for *com would only be there if it was a combined crowd/com customer.  com by itself shoud NOT promote to Near Me.

**Comment by onkariauro** [comment]
Question
1. In this case we should remove the list of wifis also. As the BSP need to be explored in this case.

**Comment by garywmendel** [comment]
we should think of *com as 2 products.  one is where it is ONLY *com therefore no wifi list and one wher it is a dual-customer *com/crowd.

**Comment by onkariauro** [comment]
Done
