### ISSUE TITLE
* * - wrong message ETC

### ISSUE THREAD

**Issue by garywmendel** [garywmendel/Yopine#100]
its not an 'invalid user', its the wrong password.  in addition to changing the wording to 'Invalid Password' we need password retrieve to be here...to the right, smaller text.

![image](https://cloud.githubusercontent.com/assets/5401514/6756174/78bf5528-cefe-11e4-9a90-a9850d34b71c.png)

**Comment by onkariauro** [comment]
password retrieve is under process. Other change done. Will be reflected by 24th March.
