### ISSUE TITLE
*edu/com/crowd - image load does not allow .jpg

### ISSUE THREAD

**Issue by garywmendel** [garywmendel/Yopine#13]
seems to only allow png.  need all image file types.  well, the popular ones anyway.

**Comment by onkariauro** [comment]
It does allow other formats also rather all image formats. Can you send us the scenario and image you trying to load

**Comment by garywmendel** [comment]
ok, will try.  i could only 'see' png in the image browser window.  i tried it 2x.

**Comment by onkariauro** [comment]
Close
