### ISSUE TITLE
* * - user should be able to 'curate' their list by deleting unwanted bsp

### ISSUE THREAD

**Issue by garywmendel** [garywmendel/Yopine#19]
![image](https://cloud.githubusercontent.com/assets/5401514/5782716/74cc8a02-9d8b-11e4-88bf-5b9384d4e180.png)

**Comment by onkariauro** [comment]
User can only delete his/her own BSPs not of others.

**Comment by garywmendel** [comment]
right, but it would be good for them to be able to delete whatever they dont want to see.  i believe in the app you can delete things you dont want to see again but it doesnt delete from others, just from your VIEW of it.  this would be good for when tons and tons of content starts piling up.

**Comment by onkariauro** [comment]
Applicable to PAM

**Comment by onkariauro** [comment]
Done Closed.
