### ISSUE TITLE
*edu/crowd - wifi list

### ISSUE THREAD

**Issue by garywmendel** [garywmendel/Yopine#25]
this is the list i see from my mac
![image](https://cloud.githubusercontent.com/assets/5401514/5790002/f57ae0aa-9e52-11e4-988e-8adeb7c70a9c.png)

this is what i see in *crowd

![image](https://cloud.githubusercontent.com/assets/5401514/5790004/0b1591ee-9e53-11e4-868f-8b268b4f121d.png)

stillman said that either there are macs for all of those names (possible) or there is an error in the code.  would there be any harm in filtering out duplicates?  its confusing.  i know i only have one SSID (RepsNDems) but for all i know it has several MACs.  

im open to discussion...

**Comment by onkariauro** [comment]
Done. Updated.
