### ISSUE TITLE
* * - linked in post missing image

### ISSUE THREAD

**Issue by garywmendel** [garywmendel/Yopine#27]
![image](https://cloud.githubusercontent.com/assets/5401514/5823897/74207d0e-a0ae-11e4-9ad0-479ad028cc9b.png)

![image](https://cloud.githubusercontent.com/assets/5401514/5823882/6199b8da-a0ae-11e4-8f90-c3dd1dbf5160.png)

**Comment by onkariauro** [comment]
Done
