### ISSUE TITLE
*b  - user/keyword search to sort '...Around Me' list

### ISSUE THREAD

**Issue by garywmendel** [garywmendel/Yopine#4]
we need to be able to search for certain user or keyword in i '...Around Me.

![image](https://cloud.githubusercontent.com/assets/5401514/5777089/8989d37e-9d5d-11e4-8b0a-8060cb1b358a.png)

**Comment by garywmendel** [comment]
consider the case where there is a LONG list of bsp around you (and certainly in explore for *com).  the original WF dealt with this.
we could go back to 'right-click-search' feature.  i will WF it.

![image](https://cloud.githubusercontent.com/assets/5401514/5779559/b3074da8-9d71-11e4-80bb-0505417ba0b7.png)

**Comment by garywmendel** [comment]
this is how a user will quickly find the correct content when the list gets big.

**Comment by onkariauro** [comment]
Added Search Option in Around Me list. Closed
