### ISSUE TITLE
* * & App - image disconnect

### ISSUE THREAD

**Issue by garywmendel** [garywmendel/Yopine#41]
creating bsp in **...

![image](https://cloud.githubusercontent.com/assets/5401514/5862784/8fd339ca-a242-11e4-939b-0cfa8f48c025.png)

...may appear vastly different in App

![image](https://cloud.githubusercontent.com/assets/5401514/5862947/04158260-a244-11e4-820a-848ffab36197.png)

**Comment by onkariauro** [comment]
Done
