### ISSUE TITLE
APP - question font/size

### ISSUE THREAD

**Issue by garywmendel** [garywmendel/Yopine#48]
i dont know what font or size this is...but i would like to try it as the question text.  ours is just too thick and bulky.  please send a sample of what it would look like - or a build in dev.

![img_1633](https://cloud.githubusercontent.com/assets/5401514/5902656/490c3252-a54a-11e4-9cbf-93b102737e49.png)
![img_3833](https://cloud.githubusercontent.com/assets/5401514/5902658/4b4438bc-a54a-11e4-873f-78e1d41d2f97.png)

**Comment by onkariauro** [comment]
Done. Will be reflected in 3rd Feb Build
