### ISSUE TITLE
APP - 7 sign-up/sign-in things

### ISSUE THREAD

**Issue by garywmendel** [garywmendel/Yopine#50]
* Tap for PIN button shoulnt appear until 10 phone digit is entered.
* PIN # field shouldnt appear until Tap for PIN button is tapped
* terms/privacy font should be smaller
* username stays green if its not taken then turns red if it 'becomes' taken...which is good...but then if they leave the field a popup should say 'that Username is taken...'
* 10 digit limit on phone #. right now you can put in (i stopped counting at 152 #s).  the 11th should throw and error message
* Tap for PIN works regardless of how many digits entered
* on the Sign-In screen, the default keyboard should be the number pad. with an alpha button that brings up the alpha keyboard

![img_4267](https://cloud.githubusercontent.com/assets/5401514/5925682/533226bc-a633-11e4-9847-e1532029174f.PNG)

**Comment by onkariauro** [comment]
Done
