### ISSUE TITLE
* com - still has wifi names

### ISSUE THREAD

**Issue by garywmendel** [garywmendel/Yopine#54]
this should only occur if its a *com/crowd customer

![image](https://cloud.githubusercontent.com/assets/5401514/5941816/5ee5c23a-a6e1-11e4-978a-6047f56c8e1b.png)

**Comment by onkariauro** [comment]
Done

**Comment by garywmendel** [comment]
you should use the old version of *com for the combined *com/crowd customers.

**Comment by onkariauro** [comment]
Done
