### ISSUE TITLE
APP & * * - Near Me/BSP around me lists need to be manageable by user

### ISSUE THREAD

**Issue by garywmendel** [garywmendel/Yopine#61]
* APP - Near Me - if user deletes the poll from their view, it should not show up again on refresh.

* * - BSP around me - same

i just deleted a huge list or bsp from android...quit yopine...restarted it....and the list reappeared.

USERS MUST BE ABLE TO MANAGE THEIR PAM LISTS.

**Comment by garywmendel** [comment]
this concept works fine in iOS but not in android.

its not even an option (to delete) in the console but it NEEDS TO BE.

**Comment by onkariauro** [comment]
Done. Closed
