### ISSUE TITLE
*com - avatar should be both icons....fox news AND the Kelly File

### ISSUE THREAD

**Issue by garywmendel** [garywmendel/Yopine#7]
i can combine them or you can.

![image](https://cloud.githubusercontent.com/assets/5401514/5778260/f5675ada-9d67-11e4-99e4-4d86f4684fb5.png)

**Comment by onkariauro** [comment]
We will require single image with Kelly file and fox News

**Comment by garywmendel** [comment]
![dual-logo](https://cloud.githubusercontent.com/assets/5401514/5818334/f47c2fd8-a082-11e4-9e74-c02092e747f5.png)

**Comment by onkariauro** [comment]
Can be done from Admin Panel Now
