### ISSUE TITLE
APP - UI changes + Like + Share + fixes

### ISSUE THREAD

**Issue by garywmendel** [garywmendel/Yopine#70]
These are all priority 1 however not until the console is delivered.

![image](https://cloud.githubusercontent.com/assets/5401514/6043900/c5c28f20-ac5d-11e4-9102-4db29f329e51.png)

**Comment by kevinostrowski** [comment]
Unliked polls should have the heart w the same line weight as refresh, no?

**Comment by onkariauro** [comment]
Will be done in build - 25th Feb.
