### ISSUE TITLE
* * - wrong wording

### ISSUE THREAD

**Issue by garywmendel** [garywmendel/Yopine#75]
'Click to login to *Crowd'
'Click to login to *Edu'

![image](https://cloud.githubusercontent.com/assets/5401514/6190968/e817193e-b373-11e4-97a0-3d4326c6980f.png)

![image](https://cloud.githubusercontent.com/assets/5401514/6190978/04da86aa-b374-11e4-8911-c4474f806ea7.png)

**Comment by onkariauro** [comment]
Done
