### ISSUE TITLE
* * - all bsp should have leading vote differentiate by orange color

### ISSUE THREAD

**Issue by garywmendel** [garywmendel/Yopine#76]
option 'H' should be yopine orange to differentiate it as the vote leader

![image](https://cloud.githubusercontent.com/assets/5401514/6197706/487dd044-b3b8-11e4-84c9-944034cfb3dc.png)

**Comment by onkariauro** [comment]
Entire Vote circle should be Yopine orange

**Comment by onkariauro** [comment]
Done
