### ISSUE TITLE
APP - we need a gear/search for the 'Near Me' tab

### ISSUE THREAD

**Issue by garywmendel** [garywmendel/Yopine#77]
search bar as on explore (from gear) but its always there.
same view as explore search
list comes back as it normally would with Near Me...ie not small square summaries.

![image](https://cloud.githubusercontent.com/assets/5401514/6200955/77c6f500-b45e-11e4-8cca-8ac94a8024e8.png)

**Comment by onkariauro** [comment]
Will be done in build - 25th Feb.
