### ISSUE TITLE
MWA - vote count bug in closed poll

### ISSUE THREAD

**Issue by garywmendel** [garywmendel/Yopine#96]
web/desktop:

![messages image 7485368](https://cloud.githubusercontent.com/assets/5401514/6715875/f4c40296-cd77-11e4-9058-10da44de9624.png)

twitter browser:

![img_5448](https://cloud.githubusercontent.com/assets/5401514/6715876/f6f05bfa-cd77-11e4-9e55-6b42b7fb7bd1.PNG)

**Comment by onkariauro** [comment]
Done.
