### ISSUE TITLE
* * - i cant get 3rd poll option to appear

### ISSUE THREAD

**Issue by garywmendel** [garywmendel/Yopine#97]
![image](https://cloud.githubusercontent.com/assets/5401514/6740492/9aa6f612-ce56-11e4-80e1-5cda184755f0.png)

**Comment by kevinostrowski** [comment]
she is smokin'Kevin OstrowskistarterYopine641 S St NWWashington, DC 20001c: 310.927.4533@yoyopine


-------- Original Message --------
Subject: [Yopine] * * - i cant get 3rd poll option to appear (#97)

**Comment by onkariauro** [comment]
You need to have poll option at least 4 character long. 3 rd option appears automatically once you put 4th character.
